server:
  port: 8084

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: TRACE
    reactor.netty: TRACE

spring:
  cloud:
    gateway:
      - id: match-service
        uri: http://${MATCH_SERVICE_BASEURL:localhost:8080}
        predicate:
          - Path=/matches
        filter:
          - SetPath=/api/match